### ISSUE TITLE
最新 master 构建/安装问题：前端类型错误、npm audit 漏洞与 Python 版本文档不一致

### ISSUE THREAD

**Issue by xibian-YQ** [shenminglinyi/PlotPilot#78]
# Latest master build/setup issues found during verification

This is not UI/visual feedback. It is about the latest `master` build, setup, and security checks.

## Version Checked

- Repository: `shenminglinyi/PlotPilot`
- Branch: `master`
- Commit: `c03a0eb3aeb367ad6891d9432a72e9141afafeac`
- Commit date: `2026-04-17T07:37:39Z`
- Local clean source archive path used for verification: `PlotPilot-upstream-latest-check`

## Environment

- macOS
- Python: `3.11.15` for backend verification
- Node/npm: local npm install from `frontend/package-lock.json`

## Backend Result

Backend import works on Python 3.11:

```bash
.venv/bin/python -c "from interfaces.main import app; print(len(app.routes))"
```

Result:

```text
187
```

Targeted backend tests also passed:

```bash
.venv/bin/python -m pytest tests/unit/domain/novel/value_objects -q
.venv/bin/python -m pytest tests/unit/application/services/test_novel_service.py tests/unit/application/services/test_chapter_service.py tests/unit/application/workflows/test_auto_novel_generation_workflow.py tests/unit/application/services/test_continuous_planning_service.py -q
```

Results:

- `110 passed, 1 warning`
- `44 passed, 2 warnings`

## Issue 1: Frontend production build fails

Commands:

```bash
cd frontend
npm ci --prefer-offline
npm run build
```

Observed:

```text
src/components/stats/StatsTopBar.vue(192,21): error TS2339: Property 'generation_quality' does not exist on type '{ slug: string; title: string; total_chapters: number; completed_chapters: number; total_words: number; avg_chapter_words: number; completion_rate: number; last_updated: string; }'.
src/types/api.ts(27,15): error TS2440: Import declaration conflicts with local declaration of 'BookDesk'.
src/types/api.ts(28,15): error TS2440: Import declaration conflicts with local declaration of 'ChapterListItem'.
src/types/api.ts(37,30): error TS2304: Cannot find name 'SuccessResponse'.
```

Likely affected files:

- `frontend/src/components/stats/StatsTopBar.vue`
- `frontend/src/types/api.ts`
- `frontend/src/types/stats.ts`
- `frontend/src/types/common.ts`
- `frontend/src/types/novel.ts`
- `frontend/src/types/chapter.ts`

Notes:

- `frontend/src/types/stats.ts` defines `generation_quality?`, but the type used by `StatsTopBar.vue` appears to be a narrower stats shape without that field.
- `frontend/src/types/api.ts` imports `BookDesk` / `ChapterListItem` and also declares interfaces with the same names locally.
- `SuccessResponse` is referenced in `frontend/src/types/api.ts` but is not imported or declared in that file.

Impact:

- Latest `master` cannot produce a frontend production build.
- This blocks packaging, local verification, and deployment.

## Issue 2: `npm audit` still reports moderate/high vulnerabilities

Command:

```bash
cd frontend
npm audit --audit-level=moderate
```

Observed:

- `axios`: moderate
- `dompurify`: moderate
- `follow-redirects`: moderate
- `lodash`: high
- `lodash-es`: high
- `vite`: high

Summary:

```text
6 vulnerabilities (3 moderate, 3 high)
```

`npm audit fix` reports fixes are available.

Impact:

- Security checks fail at `moderate` threshold.
- Vite-related advisories affect dev-server file access/path handling and should be upgraded before recommending local dev usage.

## Issue 3: Python version documentation is inconsistent

Observed:

- `README.md` still says `Python 3.9+`.
- `start.sh`, `scripts/install/env_check.py`, and `CONTRIBUTING.md` say Python `3.10+`.
- Current latest code uses annotations such as `str | None` and `dict | None`; with Python 3.9 these are evaluated at import time and fail.

Python 3.9 reproduction:

```text
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

Example files:

- `application/core/dtos/chapter_generation_metrics_dto.py`
- `application/core/services/chapter_service.py`
- `interfaces/api/v1/core/chapters.py`
- `infrastructure/ai/providers/gemini_provider.py`

Expected:

- Either update all user-facing docs/check scripts to require Python 3.10+, or keep Python 3.9 support by using `from __future__ import annotations` / `Optional[...]` consistently.

**Comment by shenminglinyi** [comment]
## 分析确认 ✅

### 前端构建问题

您发现的 TypeScript 类型错误确实存在。需要修复：

1. `StatsTopBar.vue` - `generation_quality` 字段缺失
2. `api.ts` - `BookDesk`/`ChapterListItem` 导入冲突
3. `SuccessResponse` 未定义

### npm audit 漏洞

建议运行 `npm audit fix` 升级依赖。

### Python 版本文档

统一为 **Python 3.10+**：
- 代码使用了 `str | None` 语法（3.10+）
- `README.md` 需更新

感谢您的全面检查！我会安排修复这些问题。

**Comment by shenminglinyi** [comment]
已处理该 issue 中的技术项：前端生产构建已通过，npm audit 在 moderate 阈值下为 0 vulnerabilities，Python 版本文档与检查脚本已统一到当前运行链路要求的 Python 3.14.x。感谢之前的完整验证报告，先关闭该 issue。
